package uk.frequencymobile.flow.server.model;

import java.util.List;

import javax.persistence.Entity;
import javax.persistence.OneToMany;

@Entity
public class Event extends UserContent{

	@OneToMany(mappedBy="subject")
	List<Comment> comments;
	
	@OneToMany(mappedBy="subject")
	List<EventFeeling> feelings;
	
	boolean autoGenerated;

	public List<Comment> getComments() {
		return comments;
	}

	public void setComments(List<Comment> comments) {
		this.comments = comments;
	}

	public List<EventFeeling> getFeelings() {
		return feelings;
	}

	public void setFeelings(List<EventFeeling> feelings) {
		this.feelings = feelings;
	}

	public boolean isAutoGenerated() {
		return autoGenerated;
	}

	public void setAutoGenerated(boolean autoGenerated) {
		this.autoGenerated = autoGenerated;
	}
	
}