package uk.frequencymobile.flow.server.model;

import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;

@Entity
public class Event extends GenericEntity{

	@ManyToOne
	User author;
	
	String text;
	
	@Embedded
	Location location;

	String imageUrl;
	
	boolean autoGenerated;

	public User getAuthor() {
		return author;
	}

	public void setAuthor(User author) {
		this.author = author;
	}

	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public Location getLocation() {
		return location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	public String getImageUrl() {
		return imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	public boolean isAutoGenerated() {
		return autoGenerated;
	}

	public void setAutoGenerated(boolean autoGenerated) {
		this.autoGenerated = autoGenerated;
	}
	
	@Override
	public String toString() {
		return super.toString()
				+ " | " + author.id
				+ " | " + text
				+ " | " + imageUrl
				+ " | " + location;
	}
	
}