package uk.frequencymobile.flow.server.model;

import java.util.List;

import javax.persistence.Entity;
import javax.persistence.OneToMany;

@Entity
public class Event extends UserContent{

	@OneToMany(mappedBy="subject")
	List<Comment> comments;
	
	@OneToMany(mappedBy="subject")
	List<EventFeeling> feelings;
	
	boolean autoGenerated;

}