package uk.frequency.glance.server.business;

import java.util.List;

import uk.frequency.glance.server.data_access.EventDAL;
import uk.frequency.glance.server.model.Event;
import uk.frequency.glance.server.model.Location;
import uk.frequency.glance.server.model.Media;
import uk.frequency.glance.server.model.Media.MediaType;
import uk.frequency.glance.server.model.User;
import uk.frequency.glance.server.util.GoogleAPIs;

public class EventBL extends GenericBL<Event>{

	EventDAL eventDal;

	public EventBL() {
		super(new EventDAL());
		eventDal = (EventDAL)dal;
	}
	
	public List<Event> findByAuthor(long userId) {
		List<Event> list = eventDal.findByAuthor(userId);
		return list;
	}
	
	public void generateEvent(double lat, double lng, long userId){
		String imageUrl = GoogleAPIs.getStreetViewImageUrl(lat, lng); //TODO get more from google places and also streetview with different headings, choose best image somehow
		String address = GoogleAPIs.getAddress(lat, lng);
		String description = null; //TODO get from google places
		String text = "auto generated"; //TODO

		Location location = new Location();
		location.setAddress(address);
		location.setName(description);
		location.setLat(lat);
		location.setLng(lng);
		MediaType mediaType = MediaType.IMAGE;
		Media media = new Media();
		media.setType(mediaType);
		media.setUrl(imageUrl);
		User user = new User();
		user.setId(userId);
		Event event = newEntity();
		event.setAutoGenerated(true);
		event.setAuthor(user);
		event.setLocation(location);
		event.setMediaType(mediaType);
		event.setMedia(media);
		event.setText(text);
		
		makePersistent(event);
	}
	
}
