package uk.frequencymobile.flow.server.service;

import java.util.ArrayList;
import java.util.List;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;

import uk.frequencymobile.flow.server.data.EventDAO;
import uk.frequencymobile.flow.server.data.UserDAO;
import uk.frequencymobile.flow.server.model.Comment;
import uk.frequencymobile.flow.server.model.Event;
import uk.frequencymobile.flow.server.model.User;
import uk.frequencymobile.flow.server.transfer.EventDTO;


@Path("/event")
public class EventService extends GenericService<Event, EventDTO>{

	EventDAO eventDao;
	UserDAO userDao;

	public EventService() {
		super(new EventDAO());
		eventDao = (EventDAO)dao;
		userDao = new UserDAO();
	}
	
	@GET
	@Path("/user-{id}")
	public List<EventDTO> findByAuthor(@PathParam("id") long userId) {
		List<Event> list = eventDao.findByAuthor(userId);
		return toDTO(list);
	}
	
	@Override
	protected EventDTO toDTO(Event event){
		EventDTO dto = new EventDTO();
		dto.setId(event.getId());
		dto.setAuthorId(event.getAuthor().getId());
		dto.setAutoGenerated(event.isAutoGenerated());
		dto.setLocation(event.getLocation());
		dto.setMedia(event.getMedia());
		dto.setMediaType(event.getMediaType());
		dto.setText(event.getText());
		
		List<Long> commentIds = new ArrayList<Long>();
		for(Comment comment : event.getComments()){
			commentIds.add(comment.getId());
		}
		dto.setCommentIds(commentIds);
		
		return dto;
	}
	
	@Override
	protected Event fromDTO(EventDTO dto) {

		User user = new User();
		user.setId(dto.getAuthorId());
		Event event = new Event();
		event.setAuthor(user);
		event.setAutoGenerated(dto.isAutoGenerated());
		event.setLocation(dto.getLocation());
		event.setMedia(dto.getMedia());
		event.setMediaType(dto.getMediaType());
		event.setText(dto.getText());
		
		return event;
	}
	
}