//wireshark filter: 
//http.content_type == "application/json" || http.accept == "application/json"

[ {
	"author" : {
		"bgImageUrl" : "ble",
		"creationTime" : null,
		"deleted" : false,
		"feed" : [],
		"friends" : [],
		"fullName" : "Fionn",
		"id" : 1,
		"imageUrl" : "bla",
		"password" : "123",
		"settings" : null,
		"userName" : "fionn"
	},
	"autoGenerated" : false,
	"creationTime" : null,
	"deleted" : false,
	"id" : 1,
	"imageUrl" : "bla.png",
	"location" : {
		"address" : "5 Bonhill St.",
		"description" : "Google Campus",
		"lat" : 3.545484,
		"lng" : 2.546464
	},
	"text" : "Gesu Cristo, un crocodillo!"
}, {
	"author" : {
		"bgImageUrl" : "ble",
		"creationTime" : null,
		"deleted" : false,
		"feed" : [],
		"friends" : [],
		"fullName" : "Fionn",
		"id" : 1,
		"imageUrl" : "bla",
		"password" : "123",
		"settings" : null,
		"userName" : "fionn"
	},
	"autoGenerated" : false,
	"creationTime" : null,
	"deleted" : false,
	"id" : 2,
	"imageUrl" : "bla.png",
	"location" : {
		"address" : "5 Bonhill St.",
		"description" : "Google Campus",
		"lat" : 3.545484,
		"lng" : 2.546464
	},
	"text" : "blAblbalBlablb a bal abl Lablab"
}, {
	"author" : {
		"bgImageUrl" : "ble",
		"creationTime" : null,
		"deleted" : false,
		"feed" : [],
		"friends" : [],
		"fullName" : "Fionn",
		"id" : 1,
		"imageUrl" : "bla",
		"password" : "123",
		"settings" : null,
		"userName" : "fionn"
	},
	"autoGenerated" : false,
	"creationTime" : null,
	"deleted" : false,
	"id" : 3,
	"imageUrl" : "bla.png",
	"location" : {
		"address" : "5 Bonhill St.",
		"description" : "Google Campus",
		"lat" : 3.545484,
		"lng" : 2.546464
	},
	"text" : "blAblbalBlablb a bal abl Lablab"
}, {
	"author" : {
		"bgImageUrl" : "ble",
		"creationTime" : null,
		"deleted" : false,
		"feed" : [],
		"friends" : [],
		"fullName" : "Fionn",
		"id" : 1,
		"imageUrl" : "bla",
		"password" : "123",
		"settings" : null,
		"userName" : "fionn"
	},
	"autoGenerated" : false,
	"creationTime" : null,
	"deleted" : false,
	"id" : 4,
	"imageUrl" : "bla.png",
	"location" : {
		"address" : "5 Bonhill St.",
		"description" : "Google Campus",
		"lat" : 3.545484,
		"lng" : 2.546464
	},
	"text" : "blAblbalBlablb a bal abl Lablab"
}, {
	"author" : {
		"bgImageUrl" : "ble",
		"creationTime" : null,
		"deleted" : false,
		"feed" : [],
		"friends" : [],
		"fullName" : "Fionn",
		"id" : 1,
		"imageUrl" : "bla",
		"password" : "123",
		"settings" : null,
		"userName" : "fionn"
	},
	"autoGenerated" : false,
	"creationTime" : null,
	"deleted" : false,
	"id" : 5,
	"imageUrl" : "bla.png",
	"location" : {
		"address" : "5 Bonhill St.",
		"description" : "Google Campus",
		"lat" : 3.545484,
		"lng" : 2.546464
	},
	"text" : "blAblbalBlablb a bal abl Lablab"
}, {
	"author" : {
		"bgImageUrl" : "ble",
		"creationTime" : null,
		"deleted" : false,
		"feed" : [],
		"friends" : [],
		"fullName" : "Fionn",
		"id" : 1,
		"imageUrl" : "bla",
		"password" : "123",
		"settings" : null,
		"userName" : "fionn"
	},
	"autoGenerated" : false,
	"creationTime" : null,
	"deleted" : false,
	"id" : 6,
	"imageUrl" : "bla.png",
	"location" : {
		"address" : "5 Bonhill St.",
		"description" : "Google Campus",
		"lat" : 3.545484,
		"lng" : 2.546464
	},
	"text" : "blAblbalBlablb a bal abl Lablab"
}, {
	"author" : {
		"bgImageUrl" : "ble",
		"creationTime" : null,
		"deleted" : false,
		"feed" : [],
		"friends" : [],
		"fullName" : "Fionn",
		"id" : 1,
		"imageUrl" : "bla",
		"password" : "123",
		"settings" : null,
		"userName" : "fionn"
	},
	"autoGenerated" : false,
	"creationTime" : null,
	"deleted" : false,
	"id" : 7,
	"imageUrl" : "bla.png",
	"location" : {
		"address" : "5 Bonhill St.",
		"description" : "Google Campus",
		"lat" : 3.545484,
		"lng" : 2.546464
	},
	"text" : "blAblbalBlablb a bal abl Lablab"
}, {
	"author" : {
		"bgImageUrl" : "ble",
		"creationTime" : null,
		"deleted" : false,
		"feed" : [],
		"friends" : [],
		"fullName" : "Fionn",
		"id" : 1,
		"imageUrl" : "bla",
		"password" : "123",
		"settings" : null,
		"userName" : "fionn"
	},
	"autoGenerated" : false,
	"creationTime" : null,
	"deleted" : false,
	"id" : 8,
	"imageUrl" : "bla.png",
	"location" : {
		"address" : "5 Bonhill St.",
		"description" : "Google Campus",
		"lat" : 3.545484,
		"lng" : 2.546464
	},
	"text" : "blAblbalBlablb a bal abl Lablab"
}, {
	"author" : {
		"bgImageUrl" : "ble",
		"creationTime" : null,
		"deleted" : false,
		"feed" : [],
		"friends" : [],
		"fullName" : "Fionn",
		"id" : 1,
		"imageUrl" : "bla",
		"password" : "123",
		"settings" : null,
		"userName" : "fionn"
	},
	"autoGenerated" : false,
	"creationTime" : null,
	"deleted" : false,
	"id" : 9,
	"imageUrl" : "bla.png",
	"location" : {
		"address" : "5 Bonhill St.",
		"description" : "Google Campus",
		"lat" : 3.545484,
		"lng" : 2.546464
	},
	"text" : "blAblbalBlablb a bal abl Lablab"
}, {
	"author" : {
		"bgImageUrl" : "ble",
		"creationTime" : null,
		"deleted" : false,
		"feed" : [],
		"friends" : [],
		"fullName" : "Fionn",
		"id" : 1,
		"imageUrl" : "bla",
		"password" : "123",
		"settings" : null,
		"userName" : "fionn"
	},
	"autoGenerated" : false,
	"creationTime" : null,
	"deleted" : false,
	"id" : 11,
	"imageUrl" : "bla.png",
	"location" : {
		"address" : "5 Bonhill St.",
		"description" : "Google Campus",
		"lat" : 3.545484,
		"lng" : 2.546464
	},
	"text" : "blAblbalBlablb a bal abl Lablab"
}, {
	"author" : {
		"bgImageUrl" : "ble",
		"creationTime" : null,
		"deleted" : false,
		"feed" : [],
		"friends" : [],
		"fullName" : "Fionn",
		"id" : 1,
		"imageUrl" : "bla",
		"password" : "123",
		"settings" : null,
		"userName" : "fionn"
	},
	"autoGenerated" : false,
	"creationTime" : null,
	"deleted" : false,
	"id" : 13,
	"imageUrl" : "bla.png",
	"location" : {
		"address" : "5 Bonhill St.",
		"description" : "Google Campus",
		"lat" : 3.545484,
		"lng" : 2.546464
	},
	"text" : "blAblbalBlablb a bal abl Lablab"
}, {
	"author" : {
		"bgImageUrl" : "ble",
		"creationTime" : null,
		"deleted" : false,
		"feed" : [],
		"friends" : [],
		"fullName" : "Fionn",
		"id" : 1,
		"imageUrl" : "bla",
		"password" : "123",
		"settings" : null,
		"userName" : "fionn"
	},
	"autoGenerated" : false,
	"creationTime" : null,
	"deleted" : false,
	"id" : 15,
	"imageUrl" : "bla.png",
	"location" : {
		"address" : "5 Bonhill St.",
		"description" : "Google Campus",
		"lat" : 3.545484,
		"lng" : 2.546464
	},
	"text" : "blAblbalBlablb a bal abl Lablab"
} ]